#ifndef MAGGIE_STATIC_H
#define MAGGIE_STATIC_H

/* Generated by genstatic.awk from inline/Maggie.h - do not edit by hand. */
/* Static-link glue for maggie.library: library base hidden, call sites
   identical to the shared-library build. Include this instead of
   <proto/Maggie.h> and link libmaggie.a. */

#include <exec/types.h>
#include <maggie_vec.h>
#include <maggie_vertex.h>

struct MaggieVertex;
struct MaggieClippedVertex;
struct MaggieSpriteVertex;
struct SpanPosition;
struct vec3;
struct vec2;

#ifndef __NOLIBBASE__
extern struct Library *MaggieBase;
#endif

#ifndef MAGGIE_BASE_NAME
#define MAGGIE_BASE_NAME MaggieBase
#endif

/* Static context lifecycle - replaces OpenLibrary/CloseLibrary. */
struct Library *magCreateContext(void);
void            magDeleteContext(struct Library *base);

void magSetScreenMemory(APTR * pixels __asm("a0"), UWORD xres __asm("d0"), UWORD yres __asm("d1"), APTR _base __asm("a6"));
#define magSetScreenMemory(pixels, xres, yres) \
	(magSetScreenMemory)((pixels), (xres), (yres), MAGGIE_BASE_NAME)

void magSetTexture(UWORD unit __asm("d0"), UWORD data __asm("d1"), APTR _base __asm("a6"));
#define magSetTexture(unit, data) \
	(magSetTexture)((unit), (data), MAGGIE_BASE_NAME)

void magSetDrawMode(UWORD mode __asm("d0"), APTR _base __asm("a6"));
#define magSetDrawMode(mode) \
	(magSetDrawMode)((mode), MAGGIE_BASE_NAME)

void magSetRGB(ULONG rgb __asm("d0"), APTR _base __asm("a6"));
#define magSetRGB(rgb) \
	(magSetRGB)((rgb), MAGGIE_BASE_NAME)

UWORD * magGetDepthBuffer(APTR _base __asm("a6"));
#define magGetDepthBuffer() \
	(magGetDepthBuffer)(MAGGIE_BASE_NAME)

void magSetWorldMatrix(float * matrix __asm("a0"), APTR _base __asm("a6"));
#define magSetWorldMatrix(matrix) \
	(magSetWorldMatrix)((matrix), MAGGIE_BASE_NAME)

void magSetViewMatrix(float * matrix __asm("a0"), APTR _base __asm("a6"));
#define magSetViewMatrix(matrix) \
	(magSetViewMatrix)((matrix), MAGGIE_BASE_NAME)

void magSetPerspectiveMatrix(float * matrix __asm("a0"), APTR _base __asm("a6"));
#define magSetPerspectiveMatrix(matrix) \
	(magSetPerspectiveMatrix)((matrix), MAGGIE_BASE_NAME)

void magDrawTrianglesUP(struct MaggieVertex * vtx __asm("a0"), UWORD nVerts __asm("d0"), APTR _base __asm("a6"));
#define magDrawTrianglesUP(vtx, nVerts) \
	(magDrawTrianglesUP)((vtx), (nVerts), MAGGIE_BASE_NAME)

void magDrawIndexedTrianglesUP(struct MaggieVertex * vtx __asm("a0"), UWORD nVtx __asm("d0"), UWORD * indx __asm("a1"), UWORD nIndx __asm("d1"), APTR _base __asm("a6"));
#define magDrawIndexedTrianglesUP(vtx, nVtx, indx, nIndx) \
	(magDrawIndexedTrianglesUP)((vtx), (nVtx), (indx), (nIndx), MAGGIE_BASE_NAME)

void magDrawIndexedPolygonsUP(struct MaggieVertex * vtx __asm("a0"), UWORD nVtx __asm("d0"), UWORD * indx __asm("a1"), UWORD nIndx __asm("d1"), APTR _base __asm("a6"));
#define magDrawIndexedPolygonsUP(vtx, nVtx, indx, nIndx) \
	(magDrawIndexedPolygonsUP)((vtx), (nVtx), (indx), (nIndx), MAGGIE_BASE_NAME)

void magSetVertexBuffer(WORD vBuffer __asm("d0"), APTR _base __asm("a6"));
#define magSetVertexBuffer(vBuffer) \
	(magSetVertexBuffer)((vBuffer), MAGGIE_BASE_NAME)

void magSetIndexBuffer(WORD iBuffer __asm("d0"), APTR _base __asm("a6"));
#define magSetIndexBuffer(iBuffer) \
	(magSetIndexBuffer)((iBuffer), MAGGIE_BASE_NAME)

void magDrawTriangles(UWORD startVtx __asm("d0"), UWORD nVtx __asm("d1"), APTR _base __asm("a6"));
#define magDrawTriangles(startVtx, nVtx) \
	(magDrawTriangles)((startVtx), (nVtx), MAGGIE_BASE_NAME)

void magDrawIndexedTriangles(UWORD firstVtx __asm("d0"), UWORD nVtx __asm("d1"), UWORD startIndx __asm("d2"), UWORD nIndx __asm("d3"), APTR _base __asm("a6"));
#define magDrawIndexedTriangles(firstVtx, nVtx, startIndx, nIndx) \
	(magDrawIndexedTriangles)((firstVtx), (nVtx), (startIndx), (nIndx), MAGGIE_BASE_NAME)

void magDrawIndexedPolygons(UWORD firstVtx __asm("d0"), UWORD nVtx __asm("d1"), UWORD startIndx __asm("d2"), UWORD nIndx __asm("d3"), APTR _base __asm("a6"));
#define magDrawIndexedPolygons(firstVtx, nVtx, startIndx, nIndx) \
	(magDrawIndexedPolygons)((firstVtx), (nVtx), (startIndx), (nIndx), MAGGIE_BASE_NAME)

void magDrawLinearSpan(struct SpanPosition * start __asm("a0"), struct SpanPosition * end __asm("a1"), APTR _base __asm("a6"));
#define magDrawLinearSpan(start, end) \
	(magDrawLinearSpan)((start), (end), MAGGIE_BASE_NAME)

void magDrawSpan(struct MaggieClippedVertex * start __asm("a0"), struct MaggieClippedVertex * end __asm("a1"), APTR _base __asm("a6"));
#define magDrawSpan(start, end) \
	(magDrawSpan)((start), (end), MAGGIE_BASE_NAME)

UWORD magAllocateVertexBuffer(UWORD nVerts __asm("d0"), APTR _base __asm("a6"));
#define magAllocateVertexBuffer(nVerts) \
	(magAllocateVertexBuffer)((nVerts), MAGGIE_BASE_NAME)

void magUploadVertexBuffer(UWORD vBuffer __asm("d0"), struct MaggieVertex * vtx __asm("a0"), UWORD startVtx __asm("d1"), UWORD nVerts __asm("d2"), APTR _base __asm("a6"));
#define magUploadVertexBuffer(vBuffer, vtx, startVtx, nVerts) \
	(magUploadVertexBuffer)((vBuffer), (vtx), (startVtx), (nVerts), MAGGIE_BASE_NAME)

void magFreeVertexBuffer(UWORD vBuffer __asm("d0"), APTR _base __asm("a6"));
#define magFreeVertexBuffer(vBuffer) \
	(magFreeVertexBuffer)((vBuffer), MAGGIE_BASE_NAME)

UWORD magAllocateIndexBuffer(UWORD nIndx __asm("d0"), APTR _base __asm("a6"));
#define magAllocateIndexBuffer(nIndx) \
	(magAllocateIndexBuffer)((nIndx), MAGGIE_BASE_NAME)

void magUploadIndexBuffer(UWORD iBuffer __asm("d0"), UWORD * indx __asm("a0"), UWORD startIndx __asm("d1"), UWORD nIndx __asm("d2"), APTR _base __asm("a6"));
#define magUploadIndexBuffer(iBuffer, indx, startIndx, nIndx) \
	(magUploadIndexBuffer)((iBuffer), (indx), (startIndx), (nIndx), MAGGIE_BASE_NAME)

void magFreeIndexBuffer(UWORD iBuffer __asm("d0"), APTR _base __asm("a6"));
#define magFreeIndexBuffer(iBuffer) \
	(magFreeIndexBuffer)((iBuffer), MAGGIE_BASE_NAME)

UWORD magAllocateTexture(UWORD size __asm("d0"), APTR _base __asm("a6"));
#define magAllocateTexture(size) \
	(magAllocateTexture)((size), MAGGIE_BASE_NAME)

void magUploadTexture(UWORD txtr __asm("d0"), UWORD mipmap __asm("d1"), APTR data __asm("a0"), UWORD format __asm("d2"), APTR _base __asm("a6"));
#define magUploadTexture(txtr, mipmap, data, format) \
	(magUploadTexture)((txtr), (mipmap), (data), (format), MAGGIE_BASE_NAME)

void magFreeTexture(UWORD txtr __asm("d0"), APTR _base __asm("a6"));
#define magFreeTexture(txtr) \
	(magFreeTexture)((txtr), MAGGIE_BASE_NAME)

void magBeginScene(APTR _base __asm("a6"));
#define magBeginScene() \
	(magBeginScene)(MAGGIE_BASE_NAME)

void magEndScene(APTR _base __asm("a6"));
#define magEndScene() \
	(magEndScene)(MAGGIE_BASE_NAME)

void magBegin(APTR _base __asm("a6"));
#define magBegin() \
	(magBegin)(MAGGIE_BASE_NAME)

void magEnd(APTR _base __asm("a6"));
#define magEnd() \
	(magEnd)(MAGGIE_BASE_NAME)

void magVertex(float x __asm("fp0"), float y __asm("fp1"), float z __asm("fp2"), APTR _base __asm("a6"));
#define magVertex(x, y, z) \
	(magVertex)((x), (y), (z), MAGGIE_BASE_NAME)

void magNormal(float x __asm("fp0"), float y __asm("fp1"), float z __asm("fp2"), APTR _base __asm("a6"));
#define magNormal(x, y, z) \
	(magNormal)((x), (y), (z), MAGGIE_BASE_NAME)

void magTexCoord(int texReg __asm("d0"), float u __asm("fp0"), float v __asm("fp1"), APTR _base __asm("a6"));
#define magTexCoord(texReg, u, v) \
	(magTexCoord)((texReg), (u), (v), MAGGIE_BASE_NAME)

void magTexCoord3(int texReg __asm("d0"), float u __asm("fp0"), float v __asm("fp1"), float w __asm("fp2"), APTR _base __asm("a6"));
#define magTexCoord3(texReg, u, v, w) \
	(magTexCoord3)((texReg), (u), (v), (w), MAGGIE_BASE_NAME)

void magColour(ULONG col __asm("d0"), APTR _base __asm("a6"));
#define magColour(col) \
	(magColour)((col), MAGGIE_BASE_NAME)

void magClear(UWORD buffers __asm("d0"), APTR _base __asm("a6"));
#define magClear(buffers) \
	(magClear)((buffers), MAGGIE_BASE_NAME)

void magSetLightType(UWORD light __asm("d0"), UWORD colour __asm("d1"), APTR _base __asm("a6"));
#define magSetLightType(light, colour) \
	(magSetLightType)((light), (colour), MAGGIE_BASE_NAME)

void magSetLightPosition(UWORD light __asm("d0"), float x __asm("fp0"), float y __asm("fp1"), float z __asm("fp2"), APTR _base __asm("a6"));
#define magSetLightPosition(light, x, y, z) \
	(magSetLightPosition)((light), (x), (y), (z), MAGGIE_BASE_NAME)

void magSetLightDirection(UWORD light __asm("d0"), float x __asm("fp0"), float y __asm("fp1"), float z __asm("fp2"), APTR _base __asm("a6"));
#define magSetLightDirection(light, x, y, z) \
	(magSetLightDirection)((light), (x), (y), (z), MAGGIE_BASE_NAME)

void magSetLightCone(UWORD light __asm("d0"), float phi __asm("fp0"), APTR _base __asm("a6"));
#define magSetLightCone(light, phi) \
	(magSetLightCone)((light), (phi), MAGGIE_BASE_NAME)

void magSetLightAttenuation(UWORD light __asm("d0"), float attenuation __asm("fp0"), APTR _base __asm("a6"));
#define magSetLightAttenuation(light, attenuation) \
	(magSetLightAttenuation)((light), (attenuation), MAGGIE_BASE_NAME)

void magSetLightColour(UWORD light __asm("d0"), ULONG colour __asm("d1"), APTR _base __asm("a6"));
#define magSetLightColour(light, colour) \
	(magSetLightColour)((light), (colour), MAGGIE_BASE_NAME)

void magClearColour(ULONG colour __asm("d0"), APTR _base __asm("a6"));
#define magClearColour(colour) \
	(magClearColour)((colour), MAGGIE_BASE_NAME)

void magClearDepth(UWORD depth __asm("d0"), APTR _base __asm("a6"));
#define magClearDepth(depth) \
	(magClearDepth)((depth), MAGGIE_BASE_NAME)

void magScissor(UWORD x0 __asm("d0"), UWORD y0 __asm("d1"), UWORD x1 __asm("d2"), UWORD y1 __asm("d3"), APTR _base __asm("a6"));
#define magScissor(x0, y0, x1, y1) \
	(magScissor)((x0), (y0), (x1), (y1), MAGGIE_BASE_NAME)

void magDrawSprites(UWORD startVtx __asm("d0"), UWORD nSprites __asm("d1"), float spriteSize __asm("fp0"), APTR _base __asm("a6"));
#define magDrawSprites(startVtx, nSprites, spriteSize) \
	(magDrawSprites)((startVtx), (nSprites), (spriteSize), MAGGIE_BASE_NAME)

void magDrawSpritesUP(struct MaggieSpriteVertex * vtx __asm("a0"), UWORD nSprites __asm("d0"), float spriteSize __asm("fp0"), APTR _base __asm("a6"));
#define magDrawSpritesUP(vtx, nSprites, spriteSize) \
	(magDrawSpritesUP)((vtx), (nSprites), (spriteSize), MAGGIE_BASE_NAME)

void magUploadVertexPositions(UWORD vBuffer __asm("d0"), struct vec3 * pos __asm("a0"), UWORD startVtx __asm("d1"), UWORD nVerts __asm("d2"), APTR _base __asm("a6"));
#define magUploadVertexPositions(vBuffer, pos, startVtx, nVerts) \
	(magUploadVertexPositions)((vBuffer), (pos), (startVtx), (nVerts), MAGGIE_BASE_NAME)

void magUploadVertexNormals(UWORD vBuffer __asm("d0"), struct vec3 * norm __asm("a0"), UWORD startVtx __asm("d1"), UWORD nVerts __asm("d2"), APTR _base __asm("a6"));
#define magUploadVertexNormals(vBuffer, norm, startVtx, nVerts) \
	(magUploadVertexNormals)((vBuffer), (norm), (startVtx), (nVerts), MAGGIE_BASE_NAME)

void magUploadVertexTexCoords2(UWORD vBuffer __asm("d0"), struct vec3 * uvs __asm("a0"), UWORD startVtx __asm("d1"), UWORD nVerts __asm("d2"), APTR _base __asm("a6"));
#define magUploadVertexTexCoords2(vBuffer, uvs, startVtx, nVerts) \
	(magUploadVertexTexCoords2)((vBuffer), (uvs), (startVtx), (nVerts), MAGGIE_BASE_NAME)

void magUploadVertexTexCoords3(UWORD vBuffer __asm("d0"), struct vec2 * uvs __asm("a0"), UWORD startVtx __asm("d1"), UWORD nVerts __asm("d2"), APTR _base __asm("a6"));
#define magUploadVertexTexCoords3(vBuffer, uvs, startVtx, nVerts) \
	(magUploadVertexTexCoords3)((vBuffer), (uvs), (startVtx), (nVerts), MAGGIE_BASE_NAME)

void magUploadVertexColours(UWORD vBuffer __asm("d0"), ULONG * colours __asm("a0"), UWORD startVtx __asm("d1"), UWORD nVerts __asm("d2"), APTR _base __asm("a6"));
#define magUploadVertexColours(vBuffer, colours, startVtx, nVerts) \
	(magUploadVertexColours)((vBuffer), (colours), (startVtx), (nVerts), MAGGIE_BASE_NAME)

#endif /* MAGGIE_STATIC_H */
