# genstatic.awk - generate the static-link header for maggie.library.
#
# Reads the fd2pragma-generated inline glue (inline/Maggie.h) and, for every
# LPx / LPxNR entry, emits a register-pinned prototype plus a base-hiding macro
# that direct-calls the real symbol with the global library base appended as the
# a6 argument. This lets host code link libmaggie.a and keep the exact same
# call-site syntax as the shared-library build (magFoo(args), base hidden).
#
# Driven from the same inline/Maggie.h that fd2pragma builds from maggie.fd, so
# it stays in ABI lockstep automatically.
#
# Usage: awk -f genstatic.awk inline/Maggie.h > maggie_static.h

BEGIN {
	print "#ifndef MAGGIE_STATIC_H"
	print "#define MAGGIE_STATIC_H"
	print ""
	print "/* Generated by genstatic.awk from inline/Maggie.h - do not edit by hand. */"
	print "/* Static-link glue for maggie.library: library base hidden, call sites"
	print "   identical to the shared-library build. Include this instead of"
	print "   <proto/Maggie.h> and link libmaggie.a. */"
	print ""
	print "#include <exec/types.h>"
	print "#include <maggie_vec.h>"
	print "#include <maggie_vertex.h>"
	print ""
	print "struct MaggieVertex;"
	print "struct MaggieClippedVertex;"
	print "struct MaggieSpriteVertex;"
	print "struct SpanPosition;"
	print "struct vec3;"
	print "struct vec2;"
	print ""
	print "#ifndef __NOLIBBASE__"
	print "extern struct Library *MaggieBase;"
	print "#endif"
	print ""
	print "#ifndef MAGGIE_BASE_NAME"
	print "#define MAGGIE_BASE_NAME MaggieBase"
	print "#endif"
	print ""
	print "/* Static context lifecycle - replaces OpenLibrary/CloseLibrary. */"
	print "struct Library *magCreateContext(void);"
	print "void            magDeleteContext(struct Library *base);"
	print ""
	inblock = 0
	buf = ""
}

/^#define mag[A-Z]/ { inblock = 1; buf = "" }

inblock {
	line = $0
	sub(/\\[ \t]*$/, "", line)          # strip trailing line-continuation backslash
	buf = buf " " line
	if (index($0, "MAGGIE_BASE_NAME") > 0) {
		emit(buf)
		inblock = 0
		buf = ""
	}
	next
}

function emit(b,   lp, n, nr, inner, nf, f, i, ret, name, proto, call, params) {
	if (match(b, /LP[0-9]+[A-Z]*\(/) == 0)
		return
	lp = substr(b, RSTART, RLENGTH)     # e.g. "LP3NR(" or "LP1(" or "LP0("
	nr = (index(lp, "NR") > 0)
	n = lp
	sub(/^LP/, "", n)
	sub(/[^0-9].*$/, "", n)             # leading digits only
	n = n + 0

	inner = substr(b, RSTART + RLENGTH) # everything after "LPx("
	sub(/\).*$/, "", inner)             # drop the closing ) and trailing text
	nf = split(inner, f, ",")
	for (i = 1; i <= nf; i++)
		gsub(/^[ \t]+|[ \t]+$/, "", f[i])

	if (nr) { ret = "void";  name = f[2]; ti = 3 }
	else    { ret = f[2];    name = f[3]; ti = 4 }

	proto = ret " " name "("
	call  = "(" name ")("
	params = ""
	for (i = 0; i < n; i++) {
		if (i > 0) { proto = proto ", "; call = call ", "; params = params ", " }
		proto  = proto f[ti + i*3] " " f[ti + i*3 + 1] " __asm(\"" f[ti + i*3 + 2] "\")"
		call   = call "(" f[ti + i*3 + 1] ")"
		params = params f[ti + i*3 + 1]
	}
	if (n > 0) { proto = proto ", "; call = call ", " }
	proto = proto "APTR _base __asm(\"a6\"))"
	call  = call "MAGGIE_BASE_NAME)"

	print proto ";"
	print "#define " name "(" params ") \\"
	print "\t" call
	print ""
}

END {
	print "#endif /* MAGGIE_STATIC_H */"
}
